# Generated by Django 3.1.4 on 2020-12-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='grampanchayat',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
