# Generated by Django 3.1.4 on 2020-12-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20201220_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grampanchayat',
            name='username',
            field=models.TextField(),
        ),
    ]
