# Generated by Django 3.1.4 on 2020-12-20 05:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20201220_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grampanchayat',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '1234567890'. Up to 10 digits allowed.", regex='^\\d{10,10}$')]),
        ),
        migrations.CreateModel(
            name='AccountantApprovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_status', models.CharField(choices=[('yes', 'yes')], max_length=1000)),
                ('date', models.DateTimeField(auto_now=True)),
                ('accountant_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.accountant', verbose_name='approve_accountant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='accountant_approvel')),
            ],
        ),
    ]
