# Generated by Django 3.1.4 on 2020-12-20 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20201220_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountantapprovel',
            name='accountant_status',
        ),
        migrations.AlterField(
            model_name='accountantapprovel',
            name='account_status',
            field=models.CharField(choices=[('matched', 'Matched'), ('unmatched', 'Unmatched')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='accountantapprovel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.grampanchayat', verbose_name='accountant_approvel'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.grampanchayat', verbose_name='user_agency'),
        ),
        migrations.AlterField(
            model_name='auditdocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.grampanchayat', verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.grampanchayat', verbose_name='certificate'),
        ),
        migrations.AlterField(
            model_name='directorapprovel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.grampanchayat', verbose_name='director_approvel'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.grampanchayat', verbose_name='user_payment'),
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.grampanchayat', verbose_name='pay_status'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.grampanchayat', verbose_name='user_phase'),
        ),
        migrations.AlterField(
            model_name='trainning',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.grampanchayat', verbose_name='training'),
        ),
    ]
