# Generated by Django 3.1.4 on 2020-12-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_remove_paymentstatus_paystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountantapprovel',
            name='remark',
            field=models.TextField(default='paid'),
        ),
        migrations.DeleteModel(
            name='PaymentStatus',
        ),
    ]
