# Generated by Django 3.1.4 on 2020-12-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20201221_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directorapprovel',
            name='accountant_status',
        ),
        migrations.AlterField(
            model_name='accountantapprovel',
            name='remark',
            field=models.CharField(default='paid', max_length=50),
        ),
    ]
