# Generated by Django 3.1.4 on 2020-12-28 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_auto_20201228_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portal.grampanchayat', verbose_name='gp_payment'),
        ),
    ]
