# Generated by Django 3.1.4 on 2020-12-30 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20201229_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountantapprovel',
            name='gp_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='portal.grampanchayat', verbose_name='grampanchayat_user'),
        ),
    ]
