# Generated by Django 3.1.4 on 2020-12-30 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_accountantapprovel_gp_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountantapprovel',
            name='user',
        ),
        migrations.AlterField(
            model_name='accountantapprovel',
            name='gp_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portal.grampanchayat', verbose_name='accontant_app'),
        ),
    ]
