# Generated by Django 3.1.4 on 2020-12-31 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_auto_20201230_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directorapprovel',
            name='district',
        ),
        migrations.RemoveField(
            model_name='directorapprovel',
            name='panchayat',
        ),
        migrations.RemoveField(
            model_name='directorapprovel',
            name='taluka',
        ),
        migrations.AddField(
            model_name='directorapprovel',
            name='gp',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='portal.grampanchayat'),
        ),
    ]
