# Generated by Django 3.1.4 on 2020-12-31 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_auto_20201231_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorapprovel',
            name='gp',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='portal.grampanchayat'),
        ),
    ]
