# Generated by Django 3.1.4 on 2021-01-12 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_auto_20201231_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountantapprovel',
            name='gp_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portal.grampanchayat', verbose_name='Grampanchayat User'),
        ),
        migrations.AlterField(
            model_name='directorapprovel',
            name='gp_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.grampanchayat', verbose_name='Grampanchayat User'),
        ),
    ]
